### ISSUE TITLE
Voiceover Testing

### ISSUE THREAD

**Issue by emilylavinskas** [valeriebordeleau/portfolio-valerie-bordeleau#10]
Make sure to add an alt to your down button so that Voiceover will read it back that clicking that button brings you down the page. As well, also add an alt to the social media links because right now they're all reading just as the usernames and not what accounts they're linking too like Behance, etc. Otherwise, Voiceover read it perfectly.

**Comment by valeriebordeleau** [comment]
thanks. will do.
