### ISSUE TITLE
Android 5.0.1 Mobile

### ISSUE THREAD

**Issue by jazdown** [valeriebordeleau/portfolio-valerie-bordeleau#15]
Maybe try centering your bottom links. It just looks a little awkward off to the side. 
![screenshot_2015-10-08-08-40-14](https://cloud.githubusercontent.com/assets/6373208/10367381/2649e878-6d9e-11e5-9292-f638e6f026f0.png)

**Comment by valeriebordeleau** [comment]
will do thanks
