### ISSUE TITLE
Box Shadow in Safari

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#2]
@thomasjbradley

The box shadow on my nav bar is creating a weird extra space, but only on safari. Any idea what might be causing this? Thank-you

```
<div class="nav-bar" id="top">
        <div class="list-group text-right">
                <ul class="gutter pad-top">
                    <li class="list-group__item list-group__item--inline gutter-half"><a href="#intro" class="nav-t-item">Introduction</a></li>
                    <li class="list-group__item list-group__item--inline gutter-half"><a href="#portfolio" class="nav-t-item">Portfolio</a></li>
                    <li class="list-group__item list-group__item--inline gutter-half"><a href="#contact" class="nav-t-item">Contact</a></li>
                </ul>
        </div><!-- list group --> 
    </div><!-- nav bar --> 
```

.nav-bar {
    background-color:rgba(188, 190, 192, 0.5);
    min-height: 65px;
    box-shadow: 0px 2px 2px rgba(35, 31, 32, 0.1);
}

**Comment by thomasjbradley** [comment]
It's not the `box-shadow` but the `margin` on the `<ul>`.

**Comment by valeriebordeleau** [comment]
I tried

.ul {
    margin: 0;
    padding: 0;
}

but it still seems to have that weird space on safari

**Comment by thomasjbradley** [comment]
Double check your selector...

**Comment by valeriebordeleau** [comment]
Should I not be targeting ul's in general?

**Comment by valeriebordeleau** [comment]
Adding push-0 to the ul worked. Thanks
