### ISSUE TITLE
1px Spaces on Hover States Only 

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#20]
@Thomasjbradley

I removed thin 1px spaces from between my images (main page, portfolio images) by rounding the dimensions of the .jpeg to even non-decimal numbers, however the space returns briefly in the hover state and then disappears (Safari 9). Any idea why this might be happening? Thanks

**Comment by thomasjbradley** [comment]
I'm not sure exactly, but what if the `opacity` hover was on the `<a>` tags that surround the images instead.

**Comment by valeriebordeleau** [comment]
That doesn't seem to change anything. I guess I'll try googling it. Let me know if you have any other suggestions. Thank-you.

**Comment by thomasjbradley** [comment]
Yeah, my worry is that it's a GPU issue, when the opacity is rendered into the GPU we can see the colour switch.

I know that the grey isn't final, but what about filling the whole surrounding grid with dark grey... it may help. Because right now it's white in behind.

**Comment by valeriebordeleau** [comment]
I'm really unsure about what's going on. It must have something to do with how the browser renders the effect because it isn't doing it anymore and I haven't changed anything. I'll put the grey background there just in case though. Thanks

**Comment by valeriebordeleau** [comment]
The grey background just makes the hover state not work because it's the same colour at 100% opacity and my hover state makes it 70% and the weird gap has returned. It only sometimes shows that way so it has to be something related to the browser itself?

**Comment by thomasjbradley** [comment]
Hahaha! Right, opacity!

Yeah, my gut says it's a browser bug, maybe we should wait on it until the final images are in place and see if the problem still persists.

**Comment by valeriebordeleau** [comment]
Sounds good. Honestly I applied the background colour before it occurred to me that it was the same and would do nothing. There's no padding/margins and the jpeg has even dimensions so that's probably it
