### ISSUE TITLE
Padding-left on Down Arrow

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#21]
@Thomasjbradley

The down arrow on my main home page shrinks out to nothing as I put "width=200px, padding-left: calc(50% - 100px);" on it. I have a feeling something surrounding the arrow is causing the issue because I tried replacing the arrow with the svg code and it produced an entirely different shape from the same file that it is currently linked to. Any suggestions? Thank-you

**Comment by thomasjbradley** [comment]
Yeah, it's definitely the padding. Maybe target the surrounding `<a>` tag, put `display: block` on it and `text-align: center` instead of the padding.

**Comment by valeriebordeleau** [comment]
perfect. thanks

**Comment by valeriebordeleau** [comment]
The svg code is appearing as a solid black box. The actual link works but not plugging in it's code

**Comment by thomasjbradley** [comment]
Huh, I'm not sure. I noticed the artboard isn't aligned to `0, 0`, try fixing that… maybe…

**Comment by valeriebordeleau** [comment]
Doesn't seem to have changed anything

**Comment by thomasjbradley** [comment]
It still has negative numbers, here:
https://github.com/valeriebordeleau/portfolio-valerie-bordeleau/blob/gh-pages/index.html#L68

**Comment by valeriebordeleau** [comment]
I'm unsure what values to change I tried "0 0 40 20" but that made the whole icon disappear. And also opening it in illustrator and setting the art board to 0x 0y.

**Comment by thomasjbradley** [comment]
Did you open the original AI file, or open the SVG into Illustrator?

**Comment by valeriebordeleau** [comment]
the svg. I'll try again as an .ai

**Comment by valeriebordeleau** [comment]
![screen shot 2015-10-13 at 10 39 13 pm](https://cloud.githubusercontent.com/assets/6373198/10473599/44c9ea62-71fb-11e5-8cb2-358dec141e97.png)
![screen shot 2015-10-13 at 10 38 46 pm](https://cloud.githubusercontent.com/assets/6373198/10473600/460ef318-71fb-11e5-9056-7641f7cf0abe.png)
![screen shot 2015-10-13 at 10 38 29 pm](https://cloud.githubusercontent.com/assets/6373198/10473602/48d55c40-71fb-11e5-9c81-60c8871ea7bf.png)

Set up like this, I'm still getting negative numbers

**Comment by thomasjbradley** [comment]
Why pt instead of px? Points is a print measurement, not web.

When I open the SVG in my Illustrator, the arrow isn't centred in the artboard, it's way off the bottom left:

![screen shot 2015-10-14 at 8 36 32 am](https://cloud.githubusercontent.com/assets/105192/10483689/b2994828-724e-11e5-9e7c-221ec45281b4.png)

**Comment by valeriebordeleau** [comment]
![screen shot 2015-10-14 at 9 53 34 am](https://cloud.githubusercontent.com/assets/6373198/10485679/814101ca-7259-11e5-8f36-73f320d5d3d0.png)

Every time I save it I use the alignment tools (set to art board) and it has jumped by the time I re-open the document. I'm unsure why. It's in px, the graphic is locked, I validated my code, and it still has negative numbers.

I'll try re-watching the advanced svg videos, because I'm really unsure what's going on. The .svg documents **always** move after saves (maybe this is a setting somewhere?) but it's never caused them not to show up.

**Comment by thomasjbradley** [comment]
Did you figure it out? I can see it on the website now.

**Comment by valeriebordeleau** [comment]
It's the linked file. When I copy and paste the same exact code it doesn't work. I don't understand why. I followed your video ( https://www.youtube.com/watch?v=ypvpdYhnEy4&list=PLWjCJDeWfDdcK0q3kJyY12Wjrq0A9Ljph ) exactly. 

The values are still negative

**Comment by valeriebordeleau** [comment]
The linked files are fine as placeholders but I would really like to be able to add hover states. All my svg's are appearing as black boxes (except my social media ones which were made in the exact same way). As a temporary fix, I created a hover state by just changing the opacity of the linked svg.

**Comment by thomasjbradley** [comment]
I figured it out!

In the CSS, here:
https://github.com/valeriebordeleau/portfolio-valerie-bordeleau/blob/gh-pages/css/general.css#L44-L56

We're targeting `.st0`, I'm not sure what SVG that's for, but it's ruining the down arrow, if you comment all that stuff out the arrow works properly.

Here's a new version of the SVG, I created a new Illustrator document and copied the shape into it — it fixes the negative numbers thing.

``` xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 20">
  <style>
    .st0{fill:#5E5E5E;}
  </style>
  <path d="M1.4.8C2 .4 2.9.4 3.5.9l15.6 14.6c.3.3.7.3 1 0L36.5.9c.6-.5 1.4-.5 2.1 0 .6.5.6 1.3 0 1.8L20 19.3c-.3.3-.7.3-1 0L1.4 2.7C.9 2.1.9 1.2 1.4.8z" class="st0"/>
</svg>
```

**Comment by valeriebordeleau** [comment]
Thanks. But I'm still getting this....
![screen shot 2015-10-14 at 6 11 05 pm](https://cloud.githubusercontent.com/assets/6373198/10499550/05a19c78-729f-11e5-9f0a-e592ecc3dc98.png)

**Comment by valeriebordeleau** [comment]
Awesome, thank-you I removed .st0 from that it worked great! How is your code so much shorter than mine, is it just from using SVG OMG? I have to make a few more svg's.

**Comment by thomasjbradley** [comment]
Yeah, I just ran it through SVOMG.

**Comment by valeriebordeleau** [comment]
Okay. Huh, the first few times I did it it didn't shrink it by that much but I tried it again and it's totally fine. Thank-you for all the help.
