### ISSUE TITLE
Gitgnore File

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#22]
@thomasjbradley

There's a weird file in my repository and I can't find it anywhere in my folders. Is this meant to be there? Should changes to it be synced? Is there a way to ignore multiple file extensions? Thank-you

![screen shot 2015-10-20 at 2 21 32 pm](https://cloud.githubusercontent.com/assets/6373198/10617037/4a98f100-7736-11e5-988e-b5820b9449eb.png)
![screen shot 2015-10-20 at 2 22 27 pm](https://cloud.githubusercontent.com/assets/6373198/10617038/4c21fd32-7736-11e5-800d-78cd3ffa93d7.png)

**Comment by thomasjbradley** [comment]
Yes, the `.gitignore` file is very important — it's a hidden file.

Remember last week we went to repository settings and added `_site` into the ignore list? Well all that did was make a file named `.gitignore` and write those settings into that file.

**Comment by valeriebordeleau** [comment]
I have the _site stuff ignored, I just didn't remember seeing that file before. (I'll sync it then?) thanks
