### ISSUE TITLE
Linking between html pages with jekyll

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#23]
@thomasjbradley

I'm following along with the videos but I'm not sure why my html pages are currently linking to each other I added the extension to the links and I'm still getting a not found page

```
<a href="{{site.baseurl}}/project-1/"><img src="{{site.baseurl}}/artwork/temp.jpg" alt="Project Title" class="embed__item img-hover" ></a>

```

thanks

**Comment by thomasjbradley** [comment]
What you have written in the code above looks perfect. Where is that code inside your HTML?

**Comment by valeriebordeleau** [comment]
Line 76, it's the first portfolio filler image

**Comment by thomasjbradley** [comment]
It's different than what's written above, here's it copied from line 76:

``` html
<a href="{{site.baseurl}}project-1.html">
```

This code, from above, is good:

``` html
<a href="{{site.baseurl}}/project-1/">
```

**Comment by valeriebordeleau** [comment]
I tried it both ways just to check and forgot to sync it back afterwards. It still isn't functionally locally with the correct code.

**Comment by thomasjbradley** [comment]
It looks okay. When you click the link in your browser, what's the URL?

**Comment by valeriebordeleau** [comment]
Locally it's trying to go from http://127.0.0.1:4000/ to http://127.0.0.1:4000/project-1.html

is the .html part problematic?

**Comment by thomasjbradley** [comment]
Yeah, that's right, the `.html` part shouldn't be there.

With the code that looks like this, though, it should be working okay:

``` html
<a href="{{site.baseurl}}/project-1/">
```

**Comment by valeriebordeleau** [comment]
I'm not sure what's causing the extension to be there, do I need to change the html file itself? or all of the links first maybe?

the url http://127.0.0.1:4000/project-1/  works locally for me but the clickable link just doesn't attach to that.

**Comment by thomasjbradley** [comment]
This link, right here is good:
https://github.com/valeriebordeleau/portfolio-valerie-bordeleau/blob/gh-pages/index.html#L76

Is it the one you're clicking on?

**Comment by valeriebordeleau** [comment]
Sorry, there's some code I commented out above it that made me think I'd applied it to a different bucket. Thanks.
