### ISSUE TITLE
Wordmark position

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#24]
Hey @thomasjbradley 

every time I try to centre my word mark using 

```
left: calc(50% - 50px);

```

or 

```
padding-left: calc(50% - 50px);

```

My word mark shrinks as more padding is applied. It already has a set top padding and I don't want to make it position absolute because that causes issues on smaller screens. I don't want to px for the width because I want it to flex with the screen size. It also disappears when the unit for width is in px.

Thanks

**Comment by thomasjbradley** [comment]
Remove the `width` from `.wordmark` and put it on the `<img>` inside that `<h1>`.

**Comment by valeriebordeleau** [comment]
perfect, thank-you
