### ISSUE TITLE
Typekit fonts

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#25]
@thomasjbradley

I'm trying to hook up a type kit font to my site, though the font did change when I added the stack it seems to be going to the default sans-serif rather than the one I chose, Fira Sans 2, the body copy should match my last name in the word mark.

`<script src="https://use.typekit.net/rjo6puc.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>`

was added to my index page and 

html {
    font-family: 'fira-sans-2',sans-serif;
}

h1, h2, h3 {
    font-family:'fira-sans-2',sans-serif;
    font-weight: 400;
}

was added to the typography css page. Did I miss anything? Thanks

**Comment by thomasjbradley** [comment]
I don't know exactly without seeing how you setup your kit:
- What domains did you specify when you created it? 
- Is `fira-sans-2` exactly how Typekit wants the font to be named?

**Comment by valeriebordeleau** [comment]
Does this look correct?

![screen shot 2015-10-28 at 11 15 41 am](https://cloud.githubusercontent.com/assets/6373198/10792979/5ffc8a86-7d65-11e5-91c5-3079ed17bd22.png)
![screen shot 2015-10-28 at 11 16 25 am](https://cloud.githubusercontent.com/assets/6373198/10792978/5ffc76c2-7d65-11e5-9559-afd83cfee24e.png)

**Comment by valeriebordeleau** [comment]
I just refreshed and it swapped the fonts out, (must have taken time to publish?) thanks
