### ISSUE TITLE
Title Tags with Jekyll

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#27]
Hey @thomasjbradley

If my title tag/twitter card/fb card are all in my projects.html layout in the head element how can I change them per page? Are they not meant to be in the head element?

Thanks

**Comment by thomasjbradley** [comment]
Yeah, they definitely need to be in the `<head>` element.

Check out these videos and let me know if they help:
- https://www.youtube.com/watch?v=ra9Td0DpK0s&list=PLWjCJDeWfDdfVEcLGAfdJn_HXyM4Y7_k-&index=31
- https://www.youtube.com/watch?v=FUL9SSgMZ8Y&list=PLWjCJDeWfDdfVEcLGAfdJn_HXyM4Y7_k-&index=32
