### ISSUE TITLE
Changing Navigation + Layouts

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#28]
Hey @thomasjbradley

All of my projects share arrows as their navigation but they are going to different pages (previous and next). How would I achieve this if the nav elements are on one project layout page?

**Comment by thomasjbradley** [comment]
At the top of each portfolio piece, in its YAML data, there could be an entry for the URL of the next piece.

In this stuff:
https://github.com/valeriebordeleau/portfolio-valerie-bordeleau/blob/gh-pages/hotel.html#L2

It could be something like this:

``` yml
next: /hydro
```

Then, inside the layout, we can change the `<a href=""` to use that information:
https://github.com/valeriebordeleau/portfolio-valerie-bordeleau/blob/gh-pages/_layouts/projects.html#L59

Change it to something like this:

``` html
<a href="{{site.baseurl}}{{page.next}}/"…
```

**Comment by valeriebordeleau** [comment]
Adding the YAML stripped my page of it's css for some reason.... any idea why this might be happening?

**Comment by valeriebordeleau** [comment]
It was an extra space. Works perfectly now. thank-you
