### ISSUE TITLE
Tiny Banner on Mobile (Chrome for Latest Android)

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#29]
Hey @thomasjbradley

The main banner on my index page is super short and zoomed in (not in the center-center position either) only on my Android Phone's Chrome browser. I thought it might not support vh so I played with the height in em and it didnt change. 

Thanks

**Comment by thomasjbradley** [comment]
Hmm, I'm not sure. I think you'll have to show me in person, I don't have a device to test on.

**Comment by valeriebordeleau** [comment]
OK. I'll bring it up in class. Thanks
