### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#30]
hey @thomasjbradley
in your instructions for the 404 page you asked for a file called ".htaccess" is this just the extension or the exact file name because brackets is giving me a warning that I cant start file names with a "." 
thanks

**Comment by thomasjbradley** [comment]
Those are the Apache instructions, not the GitHub instructions, refer to the GitHub ones please:
http://learn-the-web.algonquindesign.ca/topics/404-pages/#github

**Comment by valeriebordeleau** [comment]
okay. I feel like I've missed a step but putting a wrong extension after my url does automatically redirect to my 404...thanks
