### ISSUE TITLE
Spacing in Safari

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#33]
@thomasjbradley

In safari my word mark is right up against the navigation bar for some reason. Any idea what might be causing this?

Thanks again 

![screen shot 2015-12-17 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/6373198/11881301/df769604-a4d3-11e5-85e6-a70156729845.png)

**Comment by thomasjbradley** [comment]
It seems to be because of the `padding-top`, changing that to `margin` seems to work properly.

**Comment by valeriebordeleau** [comment]
awesome thanks
