### ISSUE TITLE
Won't Load. Loads Incredibly Slow!

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-valerie-bordeleau#36]
@thomasjbradley

**Comment by valeriebordeleau** [comment]
Still an issue...fontastic was not the only problem

**Comment by thomasjbradley** [comment]
Seems to be `icons.css` a Fontastic file that's hanging for me.

**Comment by valeriebordeleau** [comment]
Same... but I've deleted all links to it, and even locally I'm still getting stuck...

**Comment by thomasjbradley** [comment]
Are you using CloudFlare?

**Comment by valeriebordeleau** [comment]
Yes

**Comment by thomasjbradley** [comment]
Try signing in an clearing the caches.

**Comment by valeriebordeleau** [comment]
Ok... I might have trouble with login.... Got to double check that info because it's saying there are no sites on my cloudflare....

**Comment by valeriebordeleau** [comment]
I grabbed my password from cloudflare using my website for info to resend the password and it's still saying 'add a site'

**Comment by valeriebordeleau** [comment]
and now I have a 404 error....
Is it possible for me to go back several commits (and re-remove fontastic)???

**Comment by valeriebordeleau** [comment]
tried to replace all files and re-sync...
![screen shot 2016-10-28 at 7 10 04 pm](https://cloud.githubusercontent.com/assets/6373198/19824990/34fdf77c-9d42-11e6-904f-679781d793d6.png)
![screen shot 2016-10-28 at 7 10 10 pm](https://cloud.githubusercontent.com/assets/6373198/19824989/34fddc56-9d42-11e6-900d-a3e22fdd1aca.png)
