### ISSUE TITLE
Triangles have gap in safari 8

### ISSUE THREAD

**Issue by dagerebe** [valeriebordeleau/portfolio-valerie-bordeleau#6]
This is what happens when the screen gets larger
<img width="239" alt="screen shot 2015-10-08 at 8 55 27 am" src="https://cloud.githubusercontent.com/assets/6340285/10366771/9198113a-6d9a-11e5-85ab-4bb8b59095ae.png">

**Comment by devonash** [comment]
Same in safari 7

**Comment by charlie-quinn** [comment]
Same for Microsoft Edge
