### ISSUE TITLE
Safari 7 Nav in footer looks awkward

### ISSUE THREAD

**Issue by devonash** [valeriebordeleau/portfolio-valerie-bordeleau#8]
![screen shot 2015-10-08 at 8 58 09 am](https://cloud.githubusercontent.com/assets/6373210/10366851/219a8876-6d9b-11e5-8729-6c5b2297f35c.png)
![screen shot 2015-10-08 at 9 02 32 am](https://cloud.githubusercontent.com/assets/6373210/10366905/5ce911d6-6d9b-11e5-9df9-25b0e33af3c7.png)

Maybe try aligning them to the centre?

**Comment by valeriebordeleau** [comment]
will do thanks
